
stages:
  prepare:
    cmd: python src/data/make_dataset.py data/raw/UCI_Credit_Card.csv data/processed/
    deps:
    - src/data/make_dataset.py
    - data/raw/UCI_Credit_Card.csv
    outs:
    - data/processed/train.csv
    - data/processed/test.csv

  train:
    cmd: python src/models/train.py --train data/processed/train.csv --test data/processed/test.csv --model-out models/credit_default_model.pkl --metrics-out models/metrics.json
    deps:
    - src/models/train.py
    - data/processed/train.csv
    - data/processed/test.csv
    outs:
    - models/credit_default_model.pkl
    metrics:
    - models/metrics.json:
        cache: false
